// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgmzrxhlzorsbjhjejnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnbXpyeGhsem9yc2JqaGplam52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTY3ODAsImV4cCI6MjA2NTU5Mjc4MH0.NQmK_PQTWbiv74Svn-g4Oeph9nYEGuCP6yfp5IGnWTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);